spring:
  datasource:
    url: jdbc:mysql://localhost:3306/farm
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: farmer
    username: farm-system

mybatis:
  check-config-location: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bjtu.afms.model

pagehelper:
  # 分页插件会自动检测当前的数据库链接，自动选择合适的分页方式（可以不设置）
  helper-dialect: mysql
  page-size-zero: false
  reasonable: true
  # 用于控制默认不带 count 查询的方法中，是否执行 count 查询，这里设置为true后，total会为-1
  default-count: false

sms:
  access-key-id: xxx
  access-key-secret: xxx
  domain: dysmsapi.aliyuncs.com
  sign-name: 养殖管理系统
  template-code:
    verify: SMS_
    alert: SMS_
    remind: SMS_

afms:
  page-size: 20