spring:
  datasource:
    url: jdbc:mysql://localhost:3306/farm
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: farmer
    username: farm-system

mybatis:
  check-config-location: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bjtu.afms.model

afms:
  verify-code-length: 6
  password-salt-length: 20
  password-hash-times: 3