spring:
  datasource:
    url: jdbc:mysql://localhost:3306/farm
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: farmer
    username: farm-system
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    

mybatis:
  check-config-location: true
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.bjtu.afms.model

pagehelper:
  # 分页插件会自动检测当前的数据库链接，自动选择合适的分页方式（可以不设置）
  helper-dialect: mysql
  page-size-zero: false
  reasonable: true
  # 用于控制默认不带 count 查询的方法中，是否执行 count 查询，这里设置为true后，total会为-1
  default-count: false

sms:
  access-key-id: LTAI5t6i5b17GPSWXLuZQTPS
  access-key-secret: xIRGezu0qjRdskCA4271MaiX53bkJs
  domain: dysmsapi.aliyuncs.com
  sign-name: 阿里云短信测试
  template-code:
    verify: SMS_238981117
    alert: SMS_238946254
    remind: SMS_238976140

afms:
  page-size: 20
  qr-code:
    width: 360
    height: 360
  default:
    maintain-interval-days: 120